services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - smart-network

  auth-service:
    image: ${DOCKER_USER}/smart-task-auth-service:${BUILD_NUMBER}
    container_name: auth-service
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongodb:27017/authdb
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - smart-network

  task-service:
    image: ${DOCKER_USER}/smart-task-task-service:${BUILD_NUMBER}
    container_name: task-service
    restart: always
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongodb:27017/taskdb
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - smart-network

  notification-service:
    image: ${DOCKER_USER}/smart-task-notification-service:${BUILD_NUMBER}
    container_name: notification-service
    restart: always
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://mongodb:27017/notificationdb
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - smart-network

  report-service:
    image: ${DOCKER_USER}/smart-task-report-service:${BUILD_NUMBER}
    container_name: report-service
    restart: always
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGO_URI=mongodb://mongodb:27017/reportdb
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - smart-network

  api-gateway:
    image: ${DOCKER_USER}/smart-task-api-gateway:${BUILD_NUMBER}
    container_name: api-gateway
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - AUTH_SERVICE_URL=http://auth-service:5001
      - TASK_SERVICE_URL=http://task-service:5002
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-service
      - task-service
    networks:
      - smart-network

volumes:
  mongo_data:

networks:
  smart-network:
    driver: bridge
