[kubernetes]
k8s-server ansible_host=3.6.87.146

[harbor]
harbor-server ansible_host=13.201.56.131

[vault]
vault-server ansible_host=3.108.223.132

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/kiaq-lap-304/k8s-aws-key-real.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
