---
- name: Prepare Kubernetes server
  hosts: kubernetes
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gpg
        state: present
